# Generated by Django 5.2.4 on 2025-07-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("nueva", "Nueva"),
                    ("pendiente", "Pendiente"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                ],
                default="nueva",
                max_length=15,
            ),
        ),
    ]
