# Generated by Django 5.2.4 on 2025-07-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_cita_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="correo",
        ),
    ]
